@startuml

interface CodingStandard {
  read_rules()
  add_rule(CodingRule)
}

class MisraCodingStandard
class CertCodingStandard

class CodingRule {
  -identification
  -description
  -category
  -classification
  -group
}

class CodingRuleViolation {
  -file
  -line
  -rule
}

class CodingRuleProfile {
  -violations
  -timestap
  save()
  print()
}

class CodingRuleParser

interface Reader {
  read_violations()
}

class MisraReader
class ResharperReader

CodingStandard <|-- MisraCodingStandard
CodingStandard <|-- CertCodingStandard
MisraCodingStandard *-- CodingRule
CertCodingStandard *-- CodingRule
CodingRuleParser -> CodingStandard
CodingRuleParser -down-> CodingRuleProfile : creates
Reader <- CodingRuleParser

CodingRuleViolation -> CodingRule : violates
CodingRuleProfile "1" o-- "*" CodingRuleViolation





Reader <|-- MisraReader
Reader <|-- ResharperReader

@enduml