name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Lint with pylint
      run: |
        poetry run pylint --rcfile=.pylintrc src
    - name: Lint with black
      run: |
        poetry run black --check --line-length 120 --diff src
        poetry run black --check --line-length 120 --diff test
    - name: Lint with pydocstyle
      run: |
        poetry run pydocstyle -e -s src
    - name: Lint with pycodestyle
      run: |
        poetry run pycodestyle --first --config=.pycodestyle src
    - name: Analyze dead code
      run: |
        poetry run vulture --min-confidence 80 src test
    - name: Analyze cohesion
      run: |
        poetry run cohesion -a 50 -d src
    - name: Analyze security flaws
      run: |
        poetry run bandit -r src
    - name: Analyze complexity
      run: |
        poetry run radon cc src
        poetry run xenon src -b B -m B -a B
    - name: Test with pytest
      run: |
        poetry run coverage run -m pytest test
        poetry run coverage report

